### ISSUE TITLE
Return SVG without writing to disk

### ISSUE THREAD

**Issue by theronic** [Macroz/tangle#2]
I want to render some graphs to SVG or PNG server-side and return them via a compojure route.

How should I use tangle to return an SVG without hitting disk with `(copy (dot->svg dot) (file "output.svg")`?

**Comment by Macroz** [comment]
Hey, good question. `dot` outputs to STDOUT if you don't tell it to save to a file. So you can indeed pipe the result (SVG or PNG) to a string or byte array that you return from your compojure route. I have done this before successfully. You can use either `dot->image` or `dot->svg`.

You may want to cache the result somewhere for a time, if you know the user may refresh a few times, so that you don't end up generating the image several times.

If you need more help, let me know!

**Comment by Macroz** [comment]
Closing inactive issue.
